### PR TITLE
Fix watch dirs external workspace

### LINKED ISSUE #83: watch_dirs feature doesn't work when running tool outside the Bazel workspace
## Description

The watch_dirs feature for lazy rebuilding doesn't work when running a tool from outside the original Bazel workspace. The wrapper script tries to locate watch directories relative to the current working directory, but when running from an unrelated directory, those paths don't exist.

## Symptom

When running a tool from outside the Bazel workspace:

```bash
$ cd /some/other/project
$ mytool --help
find: /some/other/project/packages/mytool: No such file or directory
[tool runs normally]
```

## The Problem

1. `_bazel__get_workspace_path()` searches upward from `$PWD` for a workspace file
2. When none is found, it falls back to `$PWD`
3. The script tries to watch `$PWD/<watch_dir>` which doesn't exist (causing the `find` error)
4. Auto-rebuild can never trigger because it's looking in the wrong place

The tool still works, but the watch feature silently provides no value.

## Environment

bazel_env.bzl version: 0.6.0
Bazel version: 8.1.1
OS: macOS (darwin arm64)

### PR DESCRIPTION
**Pull request by danielepolencic**
fixes #83

### CODE REVIEW

File: launcher.sh.tpl [hunk 1]
```diff
@@ -21,6 +21,26 @@ _bazel__get_workspace_path() {
   echo "$workspace"
 }
 
+# Derive the source workspace from the script's own path.
+# The script is always located at <workspace>/bazel-out/..., so we can
```
Comment (fmeum) [inline launcher.sh.tpl]: Very much a nit: The script actually lives in the output base, which can be anywhere, but it's invoked through the convenience symlink and that's what we see in the script's own path. This explains why even a custom prior base location is no problem.
